config/routes.rb
Rails.application.routes.draw do
  get 'friends/create'
  get 'friends/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "dashboard", to: "pages#dashboard", as: :dashboard

  resources :venues do
    resources :facilities, only: [:show]
  end

  resources :bookings, only: [:create, :show] do
    resources :payments, only: :new
    resources :reviews, only: [:new, :create]
  end
  post '/checkout', to: 'bookings#checkout', as: :checkout
  get 'booking_success/:id', to: 'bookings#success', as: 'booking_success'
  get 'bookings/:id/checkout_summary', to: 'bookings#checkout_summary', as: :checkout_summary

#     resources :reviews, only: [:new, :create]
#   end


  resources :friends, only: [:create, :destroy]


  # post 'slots/:id/multi_bookings', to: 'bookings#multi_create'
  get "user_dashboard", to: "pages#user_dashboard", as: :user_dashboard
  get "owner_dashboard", to: "pages#owner_dashboard", as: :owner_dashboard
  get "users_index", to: "pages#users_index", as: :users_index

  resources :venues

  resources :facilities

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user

  has_many :slots
  has_one :review 

  has_many :shared_bookings


  # all the slots in the booking will belong to the same facility, therefore we can call .first
  def venue
    slots.map { |slot| slot.facility.venue }.first
  end

  def venue_address
    return nil unless venue

    venue.address
  end

  monetize :deposit_price_cents

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  respond_to :html, :json
  #  before_action :set_facility, only: [:create]
  def create
    # @slot = Slot.find(params[:slot_id])
    slots = params[:booking][:slots]
    @booking = Booking.new(start_time: slots[0][:start_time], end_time: slots[-1][:end_time], status: "pending")
    @booking.user = current_user
    if @booking.save!
      slots.each do |slot|
        @slot = Slot.find(slot[:id])
        faciliy_price_cents = @slot.facility.deposit_price_cents
        @booking.update(deposit_price_cents: faciliy_price_cents)
        @slot.update(booked: true, booking: @booking)
      end
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          price_data: {
            currency: 'gbp',
            unit_amount: @booking.deposit_price_cents,
            product_data: {
              name: @booking.slots.first.facility.venue.name
            }
          },
          quantity: 1
        }],
        mode: 'payment',
        success_url: booking_success_url(@booking),
        cancel_url:  checkout_summary_url(@booking)
      )

      @booking.update(checkout_session_id: session.id)
      redirect_to checkout_summary_path(@booking), notice: 'Booking is successful.'
    else
      redirect_to venues_path, alert: 'Booking failed. Please try again.'
    end

    # @booking.user = current_user
    # if @booking.save
    #   @slot.update(booked: true)
    #   redirect_to checkout_summary_path, notice: 'Booking is successful.'
    # else
    #   redirect_to venues_path, alert: 'Booking failed. Please try again.'
    # end
  end

  # def multi_create
  #   if params[:bookings][:slots].present?
  #     slots = params[:bookings][:slots]
  #     slots.each do |slot|
  #       @slot = Slot.find(slot[:id])
  #       @booking = Booking.new(slot_id: slot[:id], start_time: slots[0][:start_time], end_time: slots[-1][:end_time])
  #       @booking.user = current_user
  #       @booking.save!
  #       @slot.update(booked: true)
  #     end
  #     redirect_to checkout_summary_path(@booking)
  #   end
  # end

  # def multi_create
  #   if params[:bookings][:slots].present?
  #     slots = params[:bookings][:slots]
  #     slot_ids = slots.map { |slot| slot[:id] }

  #     # Ensure slots are consecutive
  #     sorted_slots = Slot.where(id: slot_ids).order(:start_time)
  #     consecutive = sorted_slots.each_cons(2).all? do |a, b|
  #       a.end_time == b.start_time
  #     end


  #     if consecutive
  #       Booking.transaction do
  #         slots.each do |slot|
  #           @slot = Slot.find(slot[:id])
  #           @booking = Booking.new(slot_id: slot[:id], start_time: sorted_slots.first.start_time, end_time: sorted_slots.last.end_time)
  #           @booking.user = current_user
  #           @booking.save!
  #           @slot.update!(booked: true)
  #         end
  #       end
  #       redirect_to checkout_summary_path(@booking)
  #   #   else
  #   #     @slot = Slot.find(slots[0][:id])
  #   #     @facility = @slot.facility
  #   #     @venue = @facility.venue
  #   #     @date_range = (Date.today..(Date.today + 13)).to_a.map { |date| [date, date.strftime(" %A %e %B")]}
  #   #     flash[:alert] = "You can only book consecutive time slots."
  #   #     # raise
  #   #     render "facilities/show", status: :unprocessable_entity, locals: { facility: @facility, venue: @venue, date_range: @date_range}
  #   #   end
  #   # else
  #   #   flash[:alert] = "No slots selected."
  #     end
  #   end
  # end

  def checkout_summary
    @booking = Booking.find(params[:id])
    @slots = @booking.slots
    @facility = @booking.slots.first.facility
    @venue = @facility.venue
    @total_price = @slots.count * @facility.price
    @remainder = @total_price - @facility.deposit_price.to_i
  end

  def checkout
    @booking = Booking.find(params[:id])

    redirect_to new_booking_payment_path(@booking)
  end

  def success
    @booking = Booking.find(params[:id])
  end

  private
  # def set_facility
  #   @facility = Facility.find(params[:facility_id])
  # end
  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :date, :status)
  end

  def bookings_params
    params.require(:booking).permit(slots: [])
  end
end

app/views/bookings/_bookings.html.erb
<% if bookings.any? %>
  <%# <% bookings.order(created_at: :desc).each do |booking| %>
  <% bookings.each do |booking| %>
    <%# <% booking = booking[0] if booking.length >1 %>
    <div class='my-3 border-bottom border-grey booking-wrapper'>
      <div class="booking-container d-flex flex-row mb-3 ">
        <%# <div class="row w-100">
          <div class="col-2"> %>
            <%# <div class="date-group"> %>

            <%# </div> %>
          <%# </div> %>
          <%# <div class="col-7"> %>
            <div class="time-location-group" style='flex-grow: 1;'>
              <p><i class="fa-solid fa-clock"></i> <%= booking.start_time.strftime("%d-%m-%-y") %> <%= booking.start_time.strftime("%H:%M") %> - <strong><%= booking.end_time.strftime("%H:%M") %></strong></p>
              <p><i class="fa-solid fa-location-dot" style='padding-left: 2px; padding-right: 2px;'></i> <strong><%= booking.venue.name %></strong>, <%= booking.venue_address %></p>
            </div>
          <%# </div> %>
          <%# <div class="col-4">
          </div> %>
          <%# <div class="col-3"> %>
            <div class="renter-details-group">
              <% venue = booking.venue %>
              <% if booking.venue.logo.attached? %>
                <%= image_tag booking.venue.logo, class: "logo-inline" %>
              <% else %>
                <%= image_tag "venue_default_avatar.png", class: "logo-inline" %>
              <% end %>
            </div>
          <%# </div>
        </div> %>
      </div>
      <% if booking.start_time < DateTime.now && booking.review.nil? %>
        <%= link_to new_booking_review_path(booking), class: ' btn-small w-30' do %>
          Review
        <% end %>
      <% end %>
    </div>
  <% end %>
<% else %>
<%# <div class="booking-container-past mt-3"> %>
  <p>No bookings! You can book <%= link_to "here", venues_path %></p>
  <%# </div> %>
<% end %>

app/views/bookings/checkout_summary.html.erb
<%= link_to venue_facility_path(@venue, @facility) do %>
  <i class="fa-solid fa-arrow-left"></i>
  Back
<% end %>


<div class="container text-center">
  <h1 class="mt-3">Booking Details</h1>

    <% if @venue.logo.present? %>
      <%= cl_image_tag @venue.logo.key, class: "mb-3 checkout-logo" %>

    <% else %>
      <%= image_tag("venue_default_avatar.png", class: "mb-3 checkout-logo") %>
    <% end %>

        <p> <%= @booking.slots.first.facility.name.capitalize %> at <%= @booking.slots.first.facility.venue.name %> </p>
      <div class="d-flex justify-content-center gap-2">
        <p> <i class=" mr-5 fa-solid fa-location-dot"></i></p>
        <p><%= @booking.slots.first.facility.venue.address.capitalize %> </p>
      </div>
      <div class="d-flex justify-content-center gap-2">
        <p> <i class="fa-solid fa-clock"></i></p>
         <p><%= @booking.start_time.strftime("%H:%M") %> until <%= @booking.end_time.strftime("%H:%M") %></p>
      </div>

  <div class="row py-4">
    <div class="col">
      <h1>Checkout summary</h1>
      <div class="checkout-summary">
        <div class="d-flex justify-content-around">
          <div class=" text-start">
            <p><strong>Total:</strong></p>


            <p><strong>Deposit to pay now :</strong></p>
            <p>(remainder to pay at venue)</p>
          </div>
          <div class=" text-center">
            <p><strong>£<%= @total_price %></strong></p>
            <p><strong><%= humanized_money_with_symbol @booking.deposit_price %></strong></p>
            <p>£<%= @remainder %></p>
          </div>
        </div>
        <div class="text-center">
          <button id="pay" class="btn btn-primary mt-3">Pay</button>
        </div>
      </div>
      <div class="justify-content-center">
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @booking.checkout_session_id %>'

          });
        });
      </script>
    </div>
  </div>
</div>
</div>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>
<p>Slot Start Time: <%= @booking.start_time %></p>
<p>Slot End Time: <%= @booking.end_time %></p>
<p>Booking Date: <%= @booking.date %></p>
<p>Status: <%= @booking.status %></p>

<%= link_to 'Back to Facility', facility_path(@booking.slot.facility_id) %>

app/views/bookings/success.html.erb
<div class="container text-center">
  <%= image_tag "green-tick.svg",  alt: "green tick success", class: "mt-5, mb-4" %>
  <h1>congratulations!</h1>

  <p><strong>Your booking has been confirmed. Please check your email for confirmation. </strong></p>
    <% if @booking.slots.first.facility.venue.logo.present? %>
      <%= cl_image_tag @booking.slots.first.facility.venue.logo.key, class: "checkout-logo" %>

    <% else %>
      <%= image_tag("venue_default_avatar.png", class: "checkout-logo") %>
    <% end %>

  <p class= "mt-3"> <%= @booking.slots.first.facility.name.capitalize %> at <%= @booking.slots.first.facility.venue.name %> </p>
      <div class="d-flex justify-content-center gap-2">
        <p> <i class=" mr-5 fa-solid fa-location-dot"></i></p>
        <p><%= @booking.slots.first.facility.venue.address.capitalize %> </p>
      </div>
      <div class="d-flex justify-content-center gap-2">
        <p> <i class="fa-solid fa-clock"></i></p>
         <p><%= @booking.start_time.strftime("%H:%M") %> until <%= @booking.end_time.strftime("%H:%M") %></p>
      </div>

    <div class= "mt-5">
     <%= link_to 'Go to Dashboard', owner_dashboard_path,  class: 'btn-primary' if current_user.owner == true%>
    <%= link_to 'Go to Dashboard', user_dashboard_path, class: 'btn-primary' if current_user.owner == false%>
    </div>
</div>