config/routes.rb
Rails.application.routes.draw do
  get 'friends/create'
  get 'friends/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "dashboard", to: "pages#dashboard", as: :dashboard

  resources :venues do
    resources :facilities, only: [:show]
  end

  resources :bookings, only: [:create, :show] do
    resources :payments, only: :new
    resources :reviews, only: [:new, :create]
  end
  post '/checkout', to: 'bookings#checkout', as: :checkout
  get 'booking_success/:id', to: 'bookings#success', as: 'booking_success'
  get 'bookings/:id/checkout_summary', to: 'bookings#checkout_summary', as: :checkout_summary

#     resources :reviews, only: [:new, :create]
#   end


  resources :friends, only: [:create, :destroy]


  # post 'slots/:id/multi_bookings', to: 'bookings#multi_create'
  get "user_dashboard", to: "pages#user_dashboard", as: :user_dashboard
  get "owner_dashboard", to: "pages#owner_dashboard", as: :owner_dashboard
  get "users_index", to: "pages#users_index", as: :users_index

  resources :venues

  resources :facilities

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/facility.rb
class Facility < ApplicationRecord
  belongs_to :venue
  has_many :slots, dependent: :destroy
  has_many :bookings, through: :slots

  validates :name, presence: true
  validates :sport, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  # validates :deposit_price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :create_time_slots

  monetize :deposit_price_cents


def create_time_slots
  # Clear existing time slots
  self.slots.destroy_all

  time_zone = 'London'

  start_time = self.venue.opening_time.in_time_zone(time_zone)
  end_time = self.venue.closing_time.in_time_zone(time_zone)
  current_date = self.created_at.in_time_zone(time_zone).to_date

  (0..6).each do |day_offset|
    current_day = (current_date + day_offset.days).in_time_zone(time_zone)

    current_start_time = current_day.to_time + start_time.seconds_since_midnight.seconds
    current_end_time = current_day.to_time + end_time.seconds_since_midnight.seconds

    while current_start_time + self.duration.minutes <= current_end_time
      self.slots.create(start_time: current_start_time, end_time: current_start_time + self.duration.minutes)
      current_start_time += self.duration.minutes
    end
  end
end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_facility, only: [:show]


  def show
    @date_range = (Date.today..(Date.today + 6)).to_a.map { |date| [date, date.strftime(" %A %e %B")]}
    # @date_range = (Date.new(2000, 1, 1)..Date.new(2000, 1, 1) + 13).to_a.map { |date| [date, date.strftime(" %A %e %B")]}
    date = params[:date] ? Date.parse(params[:date]) : Date.today
    # @slots = Slot.on_facility(@facilities).on_date(date)
    @selected_date = date
    @booking = Booking.new
  end

  private

  def set_facility
    @facility = Facility.find(params[:id])
  end

  def facility_params
    params.require(:facility).permit(:sport)
  end
end

app/views/facilities/index.html.erb
<%= form_with url: venue_facilities_path, data: { controller: "auto-submit" },method: :get do |f| %>
  <h2> <%= @venue.name %> </h2> - <h6> <%= @venue.address %> </h6>

  <%# <% @facilities.each do |facility| %>
    <%# <h3><%= facility.sport</h3> %>

     <div class="facility-card">
  <% @venue.facilities.each do |facility| %>
    <%= link_to venue_facilities_path(@venue), class: "card mb-4 text-decoration-none text-dark" do %>
      <div class="card mb-4">
        <div class="card-header d-flex align-items-center">
          <img src="https://images.unsplash.com/photo-1612534847738-b3af9bc31f0c?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGFkZWx8ZW58MHx8MHx8fDA%3D" class="rounded-circle mr-3" alt="Avatar">
          <h2 class="h5 mb-0"> <%= facility.sport %> </h2>
        </div>
        <div>
          <p>some description to be written</p>
        </div>
      </div>
    <% end %>
  <% end %>

  <h4>What time do you want to play?</h4>
  <div class="d-flex" style="overflow-x: auto; white-space: nowrap; width: 100%;">
    <% @date_range.each do |date| %>
      <div class="date-item p-2" style="display: inline-block;">
        <%= f.radio_button :date, date[0].to_s, data: { auto_submit_target: "radio" }, checked: (date[0] == @selected_date) %>
        <%= f.label :date, date_to_spans(date[1]), value: date[0].to_s, class: "date-range-label #{"active" if date[0] == @selected_date} d-flex flex-column align-items-center" %>
      </div>
    <% end %>
  </div>

  <div class="slot-time">
    <% @slots.each do |slot| %>
     <span> <%= slot.start_time.strftime( "%l %M") %> - <%= slot.end_time.strftime( "%l %M") %></span>
    <% end %>
  </div>
<% end %>

app/views/facilities/show.html.erb
<%= link_to venue_path(@facility.venue) do %>
  <i class="fa-solid fa-arrow-left"></i>
  Back
  <% end %>
<h2><%= @facility.name %></h2>

<div class="tabs-container" id="tabs-container">
  <div class="nav nav-tabs nav-justified" id="myTab" role="tablist">
    <% @date_range.each_with_index do |date, index| %>
      <div class="nav-item" role="presentation">
        <button class="nav-link <%= 'active' if index.zero? %>" id="<%= date.first.to_s %>-tab" data-bs-toggle="tab" data-bs-target="#<%= date.first.to_s %>" type="button" role="tab" aria-controls="<%= date.first.to_s %>" aria-selected="true"><%= date[1] %></button>
      </div>
    <% end %>
  </div>
</div>


<div class="tab-content" id="myTabContent" data-controller="book-slots">
  <% @date_range.each_with_index do |date, index| %>
    <div class="tab-pane fade show <%= 'active' if index.zero? %>" id="<%= date.first.to_s %>" role="tabpanel" aria-labelledby="<%= date.first.to_s %>-tab">
      <div class="slot-time-show row align-items-start justify-content-start" style="padding-right: 0px;">
        <% @facility.slots.on_day(date.first).where(booked: false).each do |slot| %>
          <div class="col-3 mb-2" style="width: fit-content;">
            <div class="slot-box">
              <input type="checkbox" class="slot-checkbox" id="slot-<%= slot.id %>" data-book-slots-target="checkbox" data-slot-id="<%= slot.id %>" data-slot-start="<%= slot.start_time %>" data-slot-end="<%= slot.end_time %>">
              <label for="slot-<%= slot.id %>" style="font-size: 15px;"> <%= slot.start_time.strftime("%H:%M") %> - <%= slot.end_time.strftime("%H:%M") %> </label>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <button id="book-selected-slots" data-action="click->book-slots#bookSlots" class="btn btn-primary">Book Selected Slots</button>
</div>