config/routes.rb
Rails.application.routes.draw do
  get 'friends/create'
  get 'friends/destroy'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "dashboard", to: "pages#dashboard", as: :dashboard

  resources :venues do
    resources :facilities, only: [:show]
  end

  resources :bookings, only: [:create, :show] do
    resources :payments, only: :new
    resources :reviews, only: [:new, :create]
  end
  post '/checkout', to: 'bookings#checkout', as: :checkout
  get 'booking_success/:id', to: 'bookings#success', as: 'booking_success'
  get 'bookings/:id/checkout_summary', to: 'bookings#checkout_summary', as: :checkout_summary

#     resources :reviews, only: [:new, :create]
#   end


  resources :friends, only: [:create, :destroy]


  # post 'slots/:id/multi_bookings', to: 'bookings#multi_create'
  get "user_dashboard", to: "pages#user_dashboard", as: :user_dashboard
  get "owner_dashboard", to: "pages#owner_dashboard", as: :owner_dashboard
  get "users_index", to: "pages#users_index", as: :users_index

  resources :venues

  resources :facilities

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/pages/_friend_card.erb
<div class="card-user">
<% if user.logo.attached? %>
              <%= cl_image_tag user.logo.key %>
            <% else %>
              <%= image_tag "avatar_placeholder.webp" %>
            <% end %>
  <div class="card-user-infos">
    <h2> <%= user.first_name %>  <%= user.last_name %></h2>
    <%= button_to '❌', friend_path(friend), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/pages/_friends_list.erb
<div class="friends">


    <div class="user-card">
<% @friends.each do |friend| %>
    <%= render "friend_card", friend: friend, user: friend.user_1 unless friend.user_1 == current_user%>
    <%= render "friend_card", friend: friend, user:friend.user_2 unless friend.user_2 == current_user%>
    </div>
  <% end %>
</div>
</div>

app/views/pages/_owner_venue_card.erb
<div class="card-trip-owner d-flex flex-column">
  <% if venue.images.attached? %>
    <%= cl_image_tag venue.images.first.key %>
  <% else %>
    <%= image_tag("backdrop.jpg") %>
  <% end %>

  <div class="card-trip-owner-info d-flex flex-column">
    <div style="flex-grow: 1;">
      <h3><%= venue.name %></h3>
    </div>

    <div style="width: 105px;">
      <% if venue.logo.attached? %>
        <%= cl_image_tag venue.logo.key, class: "card-owner-logo" %>
      <% else %>
        <%= image_tag("venue_default_avatar.png", class: "card-owner-logo") %>
      <% end %>
    </div>
    <div class="d-flex mt-3 w-100 gap-4">
   <%= link_to venue_path(venue), class: "btn-icon" do%>
  <i class="fa-solid fa-2xl fa-eye"></i>
<% end %>
  <%= link_to edit_venue_path(venue), class: "btn-icon" do %>
  <i class="fa-solid fa-2xl fa-pen"></i>
<% end %>
   <%= link_to venue_path(venue), method: :delete, class: "btn-icon", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this venue?" } do%>
  <i class="fa-solid fa-2xl fa-trash"></i>
<% end %>
</div>
  </div>
</div>

app/views/pages/_user_card.erb
<div class="card-user">
<% if user.logo.attached? %>
              <%= cl_image_tag user.logo.key %>
            <% else %>
              <%= image_tag "avatar_placeholder.webp" %>
            <% end %>
  <div class="card-user-infos">
    <h2> <%= user.first_name %>  <%= user.last_name %></h2>
    <%= link_to 'Add ', friends_create_path(friend: { user_2_id: user }), method: :post, class: " btn btn-green btn-full-width"  %>
  </div>
</div>

app/views/pages/_users_list.erb
<div class="users">
  <% users.each do |user| %>
    <div class="user-card">
      <%= render "user_card", user: user %>
    </div>
  <% end %>
</div>
</div>

app/views/pages/_venue_list.erb
 <div class="venues">
    <% venues.each do |venue| %>
      <%= render "owner_venue_card", venue: venue %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="video-container">
    <video class="darken-video" playsinline autoplay muted loop poster="<%= asset_path('tennis-background.jpg') %>" id="bgvid">
      <source src="<%= asset_path('tennis.mp4') %>" type="video/mp4">
    </video>

    <div class="hero-content text-center align-items-center">
      <h1 class="text-white text-center pt-3">Game On...</h1>
      <h5 class="special text-white pb-3 text-center ">Book Your Sport, Anytime, Anywhere!</h5>
        <a class="mt-2 w-50 text-center btn-secondary special align-items-center" href="<%= venues_path %>">See all our venues</a>
    </div>
  </div>

<div class="about-us-container">
  <h2 class="pb-4">ABOUT US</h2>
  <div class="container">

    <!-- First Card -->
    <div class="row d-flex align-items-center">
      <div class="col-12">
        <div class="about-us-card p-3 d-flex">
          <div class="col-8">
            <h4 class="pb-2">Flexibility</h4>
            <div class="border-bottom-light"></div>
            <p class="pt-2">Anywhere, anytime. Whether it's football, tennis, padel, or any other sport.</p>
          </div>
          <div class="col-4 d-flex align-items-center justify-content-center">
          <i class="fa-solid fa-shuffle fa-2xl"></i>
          </div>
        </div>
      </div>
    </div>

    <!-- Second Card -->
    <div class="row d-flex align-items-center">
      <div class="col-12">
        <div class="about-us-card p-3 d-flex flex-row-reverse">
          <div class="col-8">
            <h4 class="pb-2">Compare</h4>
            <div class="border-bottom-light"></div>
            <p class="pt-2">Find the perfect spot for your next game by comparing price, capacity and location.</p>
          </div>
          <div class="col-4 d-flex align-items-center justify-content-center">
            <i class="fa-solid fa-2xl fa-scale-unbalanced-flip"></i>
          </div>
        </div>
      </div>
    </div>

    <!-- Third Card -->
    <div class="row d-flex align-items-center">
      <div class="col-12">
        <div class="about-us-card p-3 d-flex">
          <div class="col-8">
            <h4 class="pb-2">Sport owners</h4>
            <div class="border-bottom-light"></div>
            <p class="pt-2">As a venue owner you can list your facilities with us and make it simpler to get more visitors!</p>
          </div>
          <div class="col-4 d-flex align-items-center justify-content-center">
          <i class="fa-regular fa-2xl fa-futbol"></i>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>



  <div class="top-list-venues mt-5 pt-3">
  <div class="container">
  <h3 class="pb-1 text-black">Some of our venues</h1>
  <p> Take a look at some of our top rated venues </p>
    <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <!-- Replace static carousel items with dynamic content -->
        <% @venues.each_with_index do |venue, index| %>
          <div class="carousel-item <%= 'active' if index == 0 %>">
            <div class="card-trip">
              <% if venue.images.attached? %>
                <%= cl_image_tag venue.images.first.key %>
              <% else %>
                <%= image_tag("backdrop.jpg") %>
              <% end %>
              <div class="card-trip-infos">
                <div style="flex-grow: 1;">
                  <h3><%= venue.name %></h3>
                  <h5 class="special"><%= venue.borough %></h5>
                  <p class="pt-2"><%= venue.description %></p>
                  <p><%= venue.sports %></p>
                  <p><%= venue.opening_time.strftime("%I:%M %p") %> - <%= venue.closing_time.strftime("%I:%M %p") %></p>
                </div>
                <div style="width: 105px;">
                  <% if venue.logo.attached? %>
                    <%= cl_image_tag venue.logo.key, class: "logo" %>
                  <% else %>
                    <%= image_tag("venue_default_avatar.png", class: "logo") %>
                  <% end %>
                </div>
              </div>
              <div class="btn-area w-100">
                <a href="<%= venue_path(venue) %>" class="w-100 btn-green">See More</a>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>
</div>

app/views/pages/owner_dashboard.html.erb
<h1>Welcome <%= current_user.first_name %></h1>
<h4>Your Venues</h4>
<%= render "venue_list", venues: @venues %>
<%= link_to 'Register a new venue', new_venue_path, class: " btn-green-register"  %>

app/views/pages/user_dashboard.html.erb
<h1>Welcome <%= current_user.first_name %></h1>



<div class="accordion mt-5" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Bookings
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <%= render "bookings/bookings", bookings: @bookings %>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Past bookings
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
      <%= render "bookings/bookings", bookings: @past_bookings %></strong>

        </div>
    </div>
  </div>
  <%# <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Friends
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
      <strong><%= link_to 'Add a new friend', users_index_path, class: " btn-primary w-100"  %></strong>
         <%# <%= render "friends_list", friends: @friends %>
      <%# </div> %>
    <%# </div> %>
  <%# </div> %>
<%# </div> %>

app/views/pages/users_index.erb
 <h1 class="h2 my-3 d-flex justify-content-center">Users</h1>
<%= render "users_list", users: @users %>